// Code generated by 'yaegi extract github.com/suifengpiao14/stream/packet/yaegipacket/customfunc'. DO NOT EDIT.

package yaegipacket

import (
	"github.com/suifengpiao14/stream/packet/yaegipacket/customfunc"
	"reflect"
)

func init() {
	Symbols["github.com/suifengpiao14/stream/packet/yaegipacket/customfunc/customfunc"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"IncreaPageNumber": reflect.ValueOf(customfunc.IncreaPageNumber),
	}
}
