// Code generated by 'yaegi extract github.com/suifengpiao14/httpraw'. DO NOT EDIT.

package yaegipacket

import (
	"github.com/suifengpiao14/httpraw"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/suifengpiao14/httpraw/httpraw"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BuildRequest":            reflect.ValueOf(httpraw.BuildRequest),
		"CURL_TIMEOUT":            reflect.ValueOf(&httpraw.CURL_TIMEOUT).Elem(),
		"CurrentTime":             reflect.ValueOf(httpraw.CurrentTime),
		"DefaultPrintHttpLogInfo": reflect.ValueOf(httpraw.DefaultPrintHttpLogInfo),
		"DestructReqeust":         reflect.ValueOf(httpraw.DestructReqeust),
		"Fen2yuan":                reflect.ValueOf(httpraw.Fen2yuan),
		"FomrmatHttpRaw":          reflect.ValueOf(httpraw.FomrmatHttpRaw),
		"GetMD5LOWER":             reflect.ValueOf(httpraw.GetMD5LOWER),
		"HTTP_HEAD_BODY_DELIM":    reflect.ValueOf(constant.MakeFromLiteral("\"\\r\\n\\r\\n\"", token.STRING, 0)),
		"JsonCompact":             reflect.ValueOf(httpraw.JsonCompact),
		"LOG_INFO_CURL_RAW":       reflect.ValueOf(httpraw.LOG_INFO_CURL_RAW),
		"Linux_EOF":               reflect.ValueOf(constant.MakeFromLiteral("\"\\n\"", token.STRING, 0)),
		"LogInfoNameHttp":         reflect.ValueOf(httpraw.LogInfoNameHttp),
		"NewHttpTpl":              reflect.ValueOf(httpraw.NewHttpTpl),
		"NewTransport":            reflect.ValueOf(httpraw.NewTransport),
		"ParseResponse":           reflect.ValueOf(httpraw.ParseResponse),
		"PermanentTime":           reflect.ValueOf(httpraw.PermanentTime),
		"ReadRequest":             reflect.ValueOf(httpraw.ReadRequest),
		"RestyRequestFn":          reflect.ValueOf(httpraw.RestyRequestFn),
		"TemplatefuncMap":         reflect.ValueOf(&httpraw.TemplatefuncMap).Elem(),
		"TimestampSecond":         reflect.ValueOf(httpraw.TimestampSecond),
		"Window_EOF":              reflect.ValueOf(constant.MakeFromLiteral("\"\\r\\n\"", token.STRING, 0)),
		"WithDefault":             reflect.ValueOf(httpraw.WithDefault),
		"WithEmptyStr":            reflect.ValueOf(httpraw.WithEmptyStr),
		"WithZeroNumber":          reflect.ValueOf(httpraw.WithZeroNumber),
		"Xid":                     reflect.ValueOf(httpraw.Xid),
		"ZeroTime":                reflect.ValueOf(httpraw.ZeroTime),

		// type definitions
		"LogInfoCURLRaw":  reflect.ValueOf((*httpraw.LogInfoCURLRaw)(nil)),
		"LogInfoHttp":     reflect.ValueOf((*httpraw.LogInfoHttp)(nil)),
		"LogName":         reflect.ValueOf((*httpraw.LogName)(nil)),
		"RequestDTO":      reflect.ValueOf((*httpraw.RequestDTO)(nil)),
		"RequestFn":       reflect.ValueOf((*httpraw.RequestFn)(nil)),
		"ResponseDTO":     reflect.ValueOf((*httpraw.ResponseDTO)(nil)),
		"TransportConfig": reflect.ValueOf((*httpraw.TransportConfig)(nil)),
	}
}
