// Code generated by 'yaegi extract github.com/suifengpiao14/stream/packet/yaegipacket/customfunc'. DO NOT EDIT.

package yaegipacket

import (
	"github.com/suifengpiao14/stream/packet/yaegipacket/customfunc"
	"reflect"
)

func init() {
	Symbols["github.com/suifengpiao14/stream/packet/yaegipacket/customfunc/customfunc"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Fen2yuan":     reflect.ValueOf(customfunc.Fen2yuan),
		"GetsetJson":   reflect.ValueOf(customfunc.GetsetJson),
		"MaskFunc":     reflect.ValueOf(customfunc.MaskFunc),
		"WalkArrayMap": reflect.ValueOf(customfunc.WalkArrayMap),
	}
}
